site_name: Spt-RST-Docs
site_author: a
site_description: aaa
site_url: https://idlast.github.io/otameshi.github.io/
repo_name: Spt-RST-Docs
repo_url: https://github.com/idlast/idlast.github.io
remote_name: origin
remote_branch: main
#edit_uri: edit/release/docs/
edit_uri: ''
theme:
  name: material
  # logo: imgs/logo.svg
  # /favicon: imgs/favicon.ico
  # language: ja
  # features:
  #   - navigation.tabs
  #   - navigation.expand
  # palette:
  #   scheme: preference
  #   primary: deep orange
  #   accent: amber
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde
plugins:
  - search:
      lang:
        - ja
  - git-revision-date-localized:
      locale: ja
  - minify:
      minify_html: true
# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/roy-n-roy/
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/roy_n_roy/
#   analytics:
#     provider: google
#     property: !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_TRACKING_ID"]
extra_css:
  - styles/style.css