# この例では
# master ブランチにプッシュされたときに実行される設定にしています。
# GitHub Flow などで master ブランチにマージされる度にデプロイされます。
# 必要に応じてタグのプッシュなどに変更します。
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # Pipenv でパッケージ管理している場合を想定しています。
      - run: python -m pip install pipenv
      # Pipfile.lock を Git 管理に含めている場合を想定しています。
      - run: python -m pipenv sync --dev
      # まず、ビルドします。
      - run: python -m pipenv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # デプロイ元リポジトリーとデプロイ先が異なる場合、
          # external_repository を指定します。
          external_repository: github-user-name/github-repository-name
          # publish_branch を指定しない場合、
          # gh-pages ブランチにデプロイされます。
          publish_branch: master
          publish_dir: ./site
# Configuration
theme:
  name: 'material'
  palette:
    primary: 'Teal'
    accent: 'Deep Orange'
  language: 'ja'
  feature:
    tabs: true

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    # - 'stylesheets/extra.css'
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

extra:
  social:
    - type: 'github'
      link: 'https://https://bps-github.pstg.paas.cloud.global.fujitsu.com/squidfunk'

markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde


extra_javascript:
  - 'javascripts/extra.js'
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML

google_analytics:
  - 'UA-126129623-1'
  - 'auto'